source 'https://rubygems.org'

# Current stable version of Rails.
gem 'rails', '4.1.6'

# MariaDB doesn't have it's own gem, so we use the compliant mysql2 gem instead.
gem 'mysql2'


# Production-grade server. Combines Mongrel and event-based processing for extremely high throughput on a single thread.
gem 'thin'
gem 'em-http-request'


# Languages / Libraries
gem 'jquery-rails'
gem 'haml-rails' # Using haml-rails changes the default template engine to use haml.
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass'

# Javascript library gems
gem 'phaser-rails'

# Automatically add vendor prefixes (-moz, -webkit, -o, etc...) to CSS rules
gem 'autoprefixer-rails'


# Improved form generators that automatically format for Bootstrap.
gem 'simple_form', '~> 3.1.0.rc2'

# Enhanced and simplified searching.
gem 'ransack'


# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'


# Authentication and permissions
gem 'devise'
gem 'cancancan'
gem 'rolify'


# Allow single-table list generation
gem 'acts_as_list'

# Nicer unit testing with RSpec
gem 'rspec'

# The following gems are only loaded when running in the "development" environment.
# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',            group: :development
gem 'better_errors'
gem 'binding_of_caller'
